Task 1
kejno/nodejs-epam-2021 pull request #1
Opened 2021-03-16 10:21 UTC by Kejno

[TASK 1](https://epa.ms/nodejs19-hw1)

2021-03-17 09:07 UTC, andriikukushkin requested changes
Try to filter data using pipeline. Also please exit from process when file processing is done (like once output file is ready program should be closed).
Please check other comments too.

2021-03-17 09:07 UTC, andriikukushkin commented on task1.2.js
> +readableStream.on('data', async (chunk) => {
Using pipeline you also can filter a data.

2021-03-17 09:07 UTC, andriikukushkin commented on package.json
> +    "task1": "nodemon task1.1.js",
I can't execute `npm run task1` and `npm run task2` commands. You missed something to add.

2021-03-17 09:07 UTC, andriikukushkin commented on task1.1.js
> +// const readline = require('readline')
Why you commented this?

2021-03-17 09:30 UTC, kejno commented on package.json
> +    "task1": "nodemon task1.1.js",
Fixed. I need install nodemon in dev dep.

2021-03-17 09:31 UTC, Kejno commented on task1.1.js
> +// const readline = require('readline')
It was second decision. I deleted it

2021-03-19 08:17 UTC, Kejno commented on task1.2.js
> +readableStream.on('data', async (chunk) => {
I created pipeline.js where I implemented stream though pipeline

2021-03-22 08:30 UTC, andriikukushkin approved these changes

2021-05-28 08:06 UTC, closed without merging